# Generated by Django 5.2.3 on 2025-07-07 02:10

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diary',
            options={'ordering': ['-date'], 'verbose_name': '일기', 'verbose_name_plural': '일기들'},
        ),
        migrations.AlterField(
            model_name='diary',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='diary',
            name='emotion',
            field=models.CharField(choices=[('😁', '행복'), ('😐', '보통'), ('😞', '슬픔'), ('😭', '눈물')], max_length=2),
        ),
        migrations.AlterUniqueTogether(
            name='diary',
            unique_together={('user', 'date')},
        ),
    ]
