# Generated by Django 5.2.3 on 2025-07-07 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workout',
            options={'ordering': ['-date'], 'verbose_name': '운동 기록', 'verbose_name_plural': '운동 기록들'},
        ),
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateField(verbose_name='운동 날짜'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='duration',
            field=models.PositiveIntegerField(help_text='분 단위', verbose_name='운동 시간(분)'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='name',
            field=models.CharField(max_length=100, verbose_name='운동명'),
        ),
    ]
