# Generated by Django 5.2.3 on 2025-07-07 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_timetable_delete_lecture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timetable',
            options={'ordering': ['weekday', 'start_time'], 'verbose_name': '시간표', 'verbose_name_plural': '시간표 목록'},
        ),
    ]
