# Generated by Django 5.2.3 on 2025-07-07 02:10

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habit',
            options={'ordering': ['-date'], 'verbose_name': '습관', 'verbose_name_plural': '습관들'},
        ),
        migrations.AlterField(
            model_name='habit',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='날짜'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='is_checked',
            field=models.BooleanField(default=False, verbose_name='완료 여부'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='name',
            field=models.CharField(max_length=100, verbose_name='습관 이름'),
        ),
        migrations.AlterUniqueTogether(
            name='habit',
            unique_together={('user', 'name', 'date')},
        ),
    ]
