# Generated by Django 5.2.3 on 2025-07-07 02:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0002_alter_habit_options_alter_habit_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habit',
            options={'verbose_name': '습관', 'verbose_name_plural': '습관 목록'},
        ),
        migrations.AlterUniqueTogether(
            name='habit',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='habit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='생성일'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='habit',
            name='date',
            field=models.DateField(verbose_name='날짜'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='is_checked',
            field=models.BooleanField(default=False, verbose_name='체크 여부'),
        ),
    ]
