# Generated by Django 5.2.3 on 2025-07-07 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_plannertask_delete_planner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plannertask',
            options={'ordering': ['exam_date'], 'verbose_name': '플래너 과제', 'verbose_name_plural': '플래너 과제들'},
        ),
        migrations.AlterField(
            model_name='plannertask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='생성일'),
        ),
    ]
